[project]
name = "pytorch-tutorial"
version = "1.0.0"
description = "pytorch tutorial"
authors = [{ name = "yuta-nishi" }]
readme = "README.md"
requires-python = ">= 3.10"

[tool.black]
line-length = 90

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.ruff]
select = [
  "F", # pyflakes
  "E", # pycodestyle
  "W", # pycodestyle warnings
  "I", # isort
]
ignore = []
line-length = 90
