services:
  pytorch-tutorial:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    container_name: pytorch-tutorial
    volumes:
      - ../:/workspace
      - /home/data/yutanishi/image:/data
      # When mounting SSH, please don't publish the Docker image.
      - ~/.ssh:/home/duser/.ssh:ro
      - ~/.gitconfig:/home/duser/.gitconfig:ro
      - ~/.bashrc:/home/duser/.bashrc:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
